import {
    Radar,
    Shield,
    Lock,
    Key,
    Users,
    UserX,
    FileText,
    FileSpreadsheet,
    Download,
    Globe,
    Server,
    Database,
    Cpu,
    Terminal,
    CheckCircle2,
    XCircle,
    AlertTriangle,
    ArrowRight,
    ExternalLink,
    Copy,
    Sun,
    Moon,
    Star,
    Heart,
    Coffee,
    Github,
    Linkedin,
    Mail,
    MapPin,
    Zap,
    DollarSign,
    TrendingDown,
    BarChart3,
    PieChart,
    Eye,
    EyeOff,
    Fingerprint,
    Smartphone,
    ShieldCheck,
    ShieldAlert,
    ScrollText,
    Settings,
    BookOpen,
    Workflow,
    Layers,
    Search,
    Clock,
    Calendar,
    Tag,
} from 'lucide-react';

export const ICONS = {
    Radar,
    Shield,
    Lock,
    Key,
    Users,
    UserX,
    FileText,
    FileSpreadsheet,
    Download,
    Globe,
    Server,
    Database,
    Cpu,
    Terminal,
    CheckCircle2,
    XCircle,
    AlertTriangle,
    ArrowRight,
    ExternalLink,
    Copy,
    Sun,
    Moon,
    Star,
    Heart,
    Coffee,
    Github,
    Linkedin,
    Mail,
    MapPin,
    Zap,
    DollarSign,
    TrendingDown,
    BarChart3,
    PieChart,
    Eye,
    EyeOff,
    Fingerprint,
    Smartphone,
    ShieldCheck,
    ShieldAlert,
    ScrollText,
    Settings,
    BookOpen,
    Workflow,
    Layers,
    Search,
    Clock,
    Calendar,
    Tag,
};

export const NAV_LINKS = [
    { path: '/', label: 'Home' },
    { path: '/docs', label: 'Docs' },
    { path: '/security', label: 'Security' },
    { path: '/changelog', label: 'Changelog' },
    { path: '/author', label: 'Author' },
];
